TEMPLATEROOT = ..

# additional compilation flags
CFLAGS += -O0 -g
ASFLAGS += -g

#  project files
OBJS= $(STARTUP) blinking_lights.o
OBJS+= stm32f10x_gpio.o stm32f10x_rcc.o

# include common make file
include $(TEMPLATEROOT)/Makefile.common



